name: checkpr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deploy dependencies
        run: pip install .[deploy]
      - name: Install test dependencies
        run: pip install .[test]
      - name: Install code dependencies
        run: pip install .
      - name: Lint with pylint
        run: pylint -E src
      - name: Scan security vulnerabilities with bandit
        run: bandit -c pyproject.toml -r .
      - name: Generate coverage report
        run: pytest
